#!/usr/bin/env python3
"""Generate a combined scripts_index.inc that lists every script the firmware
knows about: the three hand-coded routines (MaterialFarmMacro, ApricotDenMacro,
ApricotDenInkbackMacro) plus every Script_<hash>.h the user-facing compiler
produced under firmware/include/.

Run from the repo root after `scripts/compile_macro.py` has populated
firmware/include/Script_*.h. Output overwrites scripts_index.inc.
"""
import argparse
import glob
import hashlib
import os
import re
import sys


def parse_macro_header(path):
    """Extract display info + the MacroStep array name from a legacy header.

    Returns (label, description, macro_array_name, step_count_name, cycle_ms_name)
    so the writer can reference them directly without re-aliasing.
    """
    base = os.path.basename(path)
    with open(path, 'r', encoding='utf-8') as fh:
        text = fh.read()
    label_match = re.search(r'// Board-resident [^\n]+', text)
    label = label_match.group(0).lstrip('/').strip() if label_match else base
    # Use the C++ array identifier as the macro pointer. MaterialFarmMacro.h
    # exposes kMaterialFarmMacro, etc.
    macro_re = re.search(r'inline constexpr\s+MacroStep\s+(k\w+)Macro\[\]', text)
    count_re = re.search(r'inline constexpr\s+size_t\s+(k\w+)StepCount', text)
    cycle_re = re.search(r'inline constexpr\s+uint32_t\s+(k\w+)CycleMs', text)
    if not (macro_re and count_re and cycle_re):
        raise ValueError(f'{path}: cannot find array/count/cycle identifiers')
    return (label, base,
            macro_re.group(1) + 'Macro',
            count_re.group(1) + 'StepCount',
            cycle_re.group(1) + 'CycleMs')


def parse_compiled_header(path):
    """Extract (label, description, macro_array, count, cycle) from a
    auto-generated Script_<hash>.h file written by scripts/compile_macro.py.
    """
    base = os.path.basename(path)
    with open(path, 'r', encoding='utf-8') as fh:
        text = fh.read()
    desc_match = re.search(r'// (.+?) \(compiled from (.+?)\)', text)
    label = desc_match.group(1).strip() if desc_match else base
    desc = label
    # Greedy \w+ captures the full C++ identifier (kScript_<hash>Macro,
    # kScript_<hash>StepCount, kScript_<hash>CycleMs). The trailing
    # Macro[] / StepCount= / CycleMs tokens in the source anchor the match.
    macro_re = re.search(r'inline constexpr\s+(?:farmers::)?MacroStep\s+(k\w+)\[\]', text)
    count_re = re.search(r'inline constexpr\s+size_t\s+(k\w+)\b', text)
    cycle_re = re.search(r'inline constexpr\s+uint32_t\s+(k\w+)\b', text)
    if not (macro_re and count_re and cycle_re):
        raise ValueError(f'{path}: cannot find array/count/cycle identifiers')
    return (label, desc,
            macro_re.group(1),
            count_re.group(1),
            cycle_re.group(1))


def find_compiled_headers(include_dir):
    return sorted(glob.glob(os.path.join(include_dir, 'Script_*.h')))


HEADER_TPL = '''\
// AUTO-GENERATED by scripts/build_scripts_index.py — do not edit.
// Lists every script the firmware knows about, in this order:
//
//   {summary}
//
// Three categories feed the registry:
//   - The three hand-coded MaterialFarm / ApricotDen / ApricotDenInkback
//     macros (kept verbatim from their original headers — they were tuned
//     by hand and ship with the project).
//   - Auto-generated Script_<hash>.h files written by compile_macro.py from
//     the user's 文字版代码 .txt collection. Adding a new script is just
//     `cp new.txt scripts/macros/ && scripts/compile_macro.py` followed by
//     `pio run`; the line below expands automatically.
//   - The display `key` field is the source filename sans extension, so the
//     web UI / firmware can refer to a script by name even after re-runs.

{includes}

namespace farmers {{
struct CompiledScript {{
  const char* key;
  const char* label;
  const char* description;
  const farmers::MacroStep* steps;
  size_t step_count;
  uint32_t cycle_ms;
}};

inline constexpr CompiledScript kCompiledScripts[] = {{{entries}}};

inline constexpr size_t kCompiledScriptCount =
    sizeof(kCompiledScripts) / sizeof(kCompiledScripts[0]);

}}  // namespace farmers
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--include', default='firmware/include')
    ap.add_argument('--output', default='firmware/include/scripts_index.inc')
    ap.add_argument('--legacy',
                    action='append',
                    default=None,
                    help='Hand-coded legacy header to wrap (may repeat)')
    args = ap.parse_args()

    if args.legacy is None:
        args.legacy = [
            os.path.join(args.include, 'MaterialFarmMacro.h'),
            os.path.join(args.include, 'ApricotDenMacro.h'),
            os.path.join(args.include, 'ApricotDenInkbackMacro.h'),
        ]

    rows = []
    includes = []

    # First the legacy macros (in the order given) — keeps the existing
    # indices (material-farm = 0, apricot-den = 1, apricot-den-inkback = 2)
    # so legacy START / START2 / START3 commands stay correct.
    for path in args.legacy:
        if not os.path.isfile(path):
            sys.stderr.write(f'WARN: legacy header missing: {path}\n')
            continue
        label, _, macro, count, cycle = parse_macro_header(path)
        base = os.path.basename(path)
        key = os.path.splitext(base)[0]
        includes.append(f'#include "{base}"')
        rows.append({
            'key': key, 'label': label, 'description': label,
            'macro': macro, 'count': count, 'cycle': cycle,
            'category': 'legacy',
        })

    # Then the user-compiled scripts.
    for path in find_compiled_headers(args.include):
        label, desc, macro, count, cycle = parse_compiled_header(path)
        base = os.path.basename(path)
        key = os.path.splitext(base)[0]
        includes.append(f'#include "{base}"')
        rows.append({
            'key': key, 'label': label, 'description': desc,
            'macro': macro, 'count': count, 'cycle': cycle,
            'category': 'compiled',
        })

    # Build entries: keep them comma-separated on long lines so the diff is
    # readable when scripts change.
    parts = []
    for i, r in enumerate(rows):
        comma = ',' if i < len(rows) - 1 else ''
        parts.append(
            f'    {{"{r["key"]}", "{r["label"]}", "{r["description"]}", '
            f'{r["macro"]}, {r["count"]}, {r["cycle"]}}}{comma}'
        )
    entries = '\n'.join(parts)
    summary = '\n//   '.join(
        f'[{r["category"]:>8}] {r["label"]}  ({r["key"]})'
        for r in rows)
    body = HEADER_TPL.format(
        includes='\n'.join(includes),
        summary=summary,
        entries=entries,
    )

    with open(args.output, 'w', encoding='utf-8') as fh:
        fh.write(body)
    sys.stderr.write(
        f'wrote {args.output} with {len(rows)} script(s) '
        f'({sum(1 for r in rows if r["category"] == "legacy")} legacy + '
        f'{sum(1 for r in rows if r["category"] == "compiled")} compiled)\n')
    return 0


if __name__ == '__main__':
    sys.exit(main())
