#!/usr/bin/env python3
"""Sync web/* into firmware/data/ before every PlatformIO build.

The web/ directory is the authoritative source for the user-facing
WebUI assets (index.html, app.js, styles.css, etc.) and firmware/
data/ is the build-time staging area that gets packaged into the
LittleFS image by `pio run -t uploadfs`. Without this sync the
board serves stale assets.

This script is wired in via platformio.ini:

    extra_scripts = pre:scripts/sync_web_data.py

so every `pio run` and `pio run -t uploadfs` reflects the latest web/
tree. Idempotent and cheap (~5 ms for the current 8-file payload).

In addition to the data mirror, this script regenerates
firmware/include/web_assets.inc with a C array literal naming every
file in web/ at sync time. web_server.cpp #includes the generated
header to register the route handlers, so adding a new file to web/
does not require a hand-edit to web_server.cpp's kStaticFiles[] list.

Files that live in firmware/data/ but are NOT derived from web/ —
currently just firmware/data/provision.html, which the AP-mode
captive portal serves directly — are appended to the generated
array by name. Hand-maintaining a per-file exclusion list would be
the same bug the original hand-maintained kStaticFiles[] had, so
those rare outliers live in a small FIXED_ASSETS tuple next to the
generator instead.
"""
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "web")
DST = os.path.join(ROOT, "firmware", "data")
INC_PATH = os.path.join(ROOT, "firmware", "include", "web_assets.inc")

# Outlier files served from firmware/data/ that have no web/ source.
# Keep this list tiny — every entry here is a file someone baked into
# the firmware directly and forgot to surface to the WebUI build.
FIXED_ASSETS = ("provision.html",)


def list_web_files(src_dir):
    """Return web/* entry names sorted, excluding directories and dotfiles."""
    if not os.path.isdir(src_dir):
        return []
    names = []
    for entry in sorted(os.listdir(src_dir)):
        if entry.startswith("."):
            continue
        if os.path.isdir(os.path.join(src_dir, entry)):
            continue
        names.append(entry)
    return names


def write_assets_inc(path, web_files, fixed_assets):
    """Emit a C array literal listing every served asset name."""
    entries = list(web_files) + list(fixed_assets)
    # Stable sort so the generated file is byte-identical across
    # rebuilds (matters for diff hygiene on the generated header).
    entries = sorted(set(entries))
    lines = [
        "// AUTO-GENERATED by scripts/sync_web_data.py — do not edit.",
        "// Source of truth is web/ (+ FIXED_ASSETS for firmware-only assets).",
        "// Regenerated every pre-build. Used by web_server.cpp to register",
        "// static-file routes; see scripts/sync_web_data.py.",
        "static const char* kStaticFiles[] = {",
    ]
    for name in entries:
        lines.append(f'    "{name}",')
    lines.append("};")
    lines.append("")
    body = "\n".join(lines)
    # Avoid touching mtime if the content is unchanged — keeps the
    # build graph tight when only unrelated files in src/ changed.
    existing = ""
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as fh:
            existing = fh.read()
    if existing == body:
        return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)
    return True


if not os.path.isdir(SRC):
    sys.exit(f"sync_web_data: source not found: {SRC}")

os.makedirs(DST, exist_ok=True)
copied = 0
for entry in os.listdir(SRC):
    src_path = os.path.join(SRC, entry)
    dst_path = os.path.join(DST, entry)
    if os.path.isdir(src_path):
        continue
    # Always overwrite the destination so the data partition
    # reflects the latest web/ tree on every build, even when the
    # source and destination mtimes are identical (copy2's default
    # is "copy only if source is newer or destination is missing",
    # which is not what we want here).
    shutil.copyfile(src_path, dst_path)
    copied += 1

inc_changed = write_assets_inc(INC_PATH, list_web_files(SRC), FIXED_ASSETS)
print(
    f"sync_web_data: refreshed {copied} file(s) from web/ to firmware/data/"
    f"{', regenerated web_assets.inc' if inc_changed else ''}",
    flush=True,
)
